name: 01-building-blocks #Namen the work flow

on: workflow_dispatch  #Add the following triggers to your workflow
    
jobs:
  echo-hello: #First job Add two jobs to the workflow
    runs-on: ubuntu-latest
    steps:
      - name: Say hello # single step 
        run: echo "Hello, world!"

  echo-goodbye: #Second Job 
    runs-on: ubuntu-latest
    steps:
      - name: Successful step #First steps
        run: |
          echo "I will succeed"
          exit 0
      
      - name: Say goodbye # Second steps 
        run: echo "Goodbye!"


