name: 02 - workflow Events

on: 
 workflow_dispatch:


  schedule:
    - cron: '*/5 * * * *'



jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: show the tigger
      run: echo "I've been triggered by a(n) ${{github.event_name}}"

 


